.TH "SOLVIEW" "1" "May 26, 2020"
.SH "NAME"
solview \- solaris system information viewer
.SH "SYNOPSIS"
solview subcommand [arguments]
.SH DESCRIPTION
The solview utility allows the user to see a graphical display of some
properties of a computer running Solaris or derivatives.
.LP
To see the available subcommands, run solview help.
.SH SEE ALSO
jkstat(1), jproc(1)
